on:
  push:
    branches:
      - lamdera-next

name: Build Linux x86_64
jobs:
  build:
    name: Build MacOS x86_64
    runs-on: lamdera-community-m1
    steps:
      - uses: actions/checkout@v3
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Run distribution script
        run: |
          ./build-linux-x86_64-musl.sh
