on:
  push:
    branches:
      - distribute

name: Build Linux arm64
jobs:
  build:
    name: Build Linux arm64
    runs-on: lamdera-community-m1
    steps:
      - uses: actions/checkout@v3
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Run distribution script
        run: |
          cd distribution
          ./build-linux-arm64-musl.sh
