on: [push]
name: build
jobs:
  runhaskell:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: stack build --only-dependencies
      - run: stack build
          timeout-minutes: 10
      - run: stack build --copy-bins
          timeout-minutes: 1
