on:
  push:
    branches:
      - distribute

name: Build Linux x86_64
jobs:
  build:
    name: Build Linux x86_64
    runs-on: lamdera-community-linux-x86_64
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_USER_SCP_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v3
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Run distribution script
        run: |
          cd distribution
          ./build-linux-x86_64-musl.sh
